all: show_hide union weekend set

show_hide: show_hide.cpp
	g++ $^ -o $@

union: union.cpp
	g++ $^ -o $@

weekend: weekend.cpp
	g++ $^ -o $@

set: set.cpp
	g++ $^ -o $@

clean:
	$(RM) -r show_hide union weekend set
